[metadata]
name = reviews_bot
version = 0.0.7
author = m.boriskin
author_email =
home_page =
description = Scrapping reviews from mobile stores
long_description = file: README.md
long_description_content_type = text/markdown
license = VK_Tech

[options]
packages = find:
python_requires = >=3.11
install_requires =
    APScheduler
    google-play-scraper
    pycryptodome
    setuptools
    loguru>=0.6.0
    prometheus_client>=0.14.1
    requests==2.26.0
    mailru-im-bot==0.0.21
    PyYAML==6.0


[options.extras_require]
dev = pre-commit==2.12.1
