DROP TABLE IF EXISTS googleplay_reviews;
DROP TABLE IF EXISTS rustore_reviews;
DROP TABLE IF EXISTS appgallery_reviews;

CREATE TABLE googleplay_reviews (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    review_id TEXT NOT NULL
);

CREATE TABLE rustore_reviews (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    review_id TEXT NOT NULL
);

CREATE TABLE appgallery_reviews (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    review_id TEXT NOT NULL
);
