[global]
index-url = https://pypi.org/simple
trusted-host = pypi.org
               pypi.python.org
               зеркало1
               зеркало2
               корпоративный_гитлаб
extra-index-url= https://pypi.python.org/simple/
                 зеркало1
                 зеркало2
                 https://корпоративный_гитлаб/api/v4/projects/21158/packages/pypi/simple
                 https://корпоративный_гитлаб/api/v4/projects/33721/packages/pypi/simple
                 https://корпоративный_гитлаб/api/v4/projects/34915/packages/pypi/simple