[global]
index-url = https://pypi.org/simple
trusted-host = pypi.org
               pypi.python.org
               зеркало1
               зеркало2
               корпоративный_гитлаб
extra-index-url= https://pypi.python.org/simple/
                 https://зеркало1/root/pypi
                 http://зеркало2/pypi_mirror/simple
                 https://корпоративный_гитлаб/api/v4/projects/айди1/packages/pypi/simple
                 https://корпоративный_гитлаб/api/v4/projects/айди2/packages/pypi/simple
                 https://корпоративный_гитлаб/api/v4/projects/айди3/packages/pypi/simple