[global]
index-url = http://зеркало/pypi_mirror/simple/
trusted-host = зеркало
               корпоративный_гитлаб
extra-index-url= https://корпоративный_гитлаб/api/v4/projects/айди/packages/pypi/simple
