[metadata]
name = serious_bot
version = 0.1.1
author = m.boriskin
author_email =
home_page =
description = Bot for Serious Reason
long_description = file: README.md
long_description_content_type = text/markdown
license = VK_Tech

[options]
packages = find:
python_requires = >=3.11
install_requires =
    APScheduler
    setuptools
    jira
    cryptography
    aiosqlite
    pytest
    asynctest
    async-retry==0.3.1.dev4
    async-timeout==4.0.3
    ProstoGitlabClient
    aiohttp==3.8.6
    pydantic==1.10.13
    python-gitlab==3.1.0
    loguru>=0.6.0
    requests
    packaging~=24.2
    mailru-im-bot==0.0.21
    PyYAML==6.0


[options.extras_require]
dev = pre-commit==2.12.1
